import { createContext, useContext, useEffect, useState } from 'react';

const messages = {
  en: {
    navRecipes: 'Recipes', navCuisines: 'Cuisines', navAbout: 'About', findMeal: 'Find your next meal', homeLabel: 'RecipeMaster home', mainNavigation: 'Main navigation', dietLabel: 'Diet', cuisineLabel: 'Cuisine', maxTimeLabel: 'Maximum cooking time', sortLabel: 'Sort recipes', searchActionLabel: 'Search recipes',
    heroEyebrow: 'A recipe home for real life', heroTitleLead: 'Turn what you have into what you can', heroTitleEm: 'cook.', heroIntro: 'A little inspiration for the ingredients already waiting in your kitchen.', heroFind: 'Find a recipe', heroNote: 'Made for everyday kitchens, wherever you are.', heroPhotoLabel: 'GOOD FOOD, LESS GUESSWORK', heroPhotoKicker: '01 / EVERYDAY', heroImageAlt: 'A bowl of homemade lentil and vegetable stew',
    flowScan: 'SCAN', flowConfirm: 'CONFIRM', flowCook: 'COOK', flowWaste: 'WASTE LESS', indexEyebrow: 'THE RECIPE INDEX', compactRecipesHeading: 'A good place to start', recipesHeading: 'Find something good', recipesCount: '{count} recipes', searchLabel: 'Search recipes or ingredients', searchPlaceholder: 'Try tomato, lentils, or rice',
    anyDiet: 'Any diet', vegetarian: 'Vegetarian', vegan: 'Vegan', glutenFree: 'Gluten-free', anyCuisine: 'Any cuisine', southIndian: 'South Indian', northIndian: 'North Indian', eastAsian: 'East Asian-inspired', tamilCuisine: 'Tamil', anyTime: 'Any time', under20: 'Under 20 min', under30: 'Under 30 min', under45: 'Under 45 min', recentlyAdded: 'Recently added', shortestTime: 'Shortest time', mostSaved: 'Most saved', search: 'Search', filterSummary: 'Made for what is already in your pantry.', clearFilters: 'Clear filters', loadingRecipes: 'Finding recipes from your kitchen…', recipesErrorTitle: 'Recipes are out of reach.', apiOffline: 'Recipe data is temporarily unavailable. Check your MongoDB connection and try again.', apiUnreachable: 'We could not reach RecipeMaster. Check that the API is running and try again.', genericLoadError: 'Something went wrong while loading recipes. Please try again.', notFoundError: 'We could not find that recipe.', tryAgain: 'Try again', quotaExceeded: 'You have used your {limit} recipe searches for today. They reset at {reset}.', noRecipes: 'No recipes found yet.', emptyRecipes: 'Try a broader search, or add original demo recipes with the seed command after connecting MongoDB.', browseAll: 'Browse the full recipe index', pageLabel: 'Page {page} of {pages}', previous: 'Previous', next: 'Next',
    worldEyebrow: 'A WORLD OF HOME COOKING', cuisineTitleFirst: 'Start with a flavour', cuisineTitleSecond: 'you love.', everydayFavourites: 'Everyday favourites', aboutEyebrow: 'A MORE THOUGHTFUL KITCHEN', aboutText: 'Cook step by step. Keep track of what you have. Let the next meal begin with the ingredients that need you first.', exploreRecipes: 'Explore recipes', footerTagline: 'Turn what you have into what you can cook.', footerCredit: 'A little less waste, one meal at a time.',
    pageEyebrow: 'COOK WITH WHAT YOU HAVE', pageTitle: 'The recipe index', pageIntro: 'Search by ingredient, find a new favourite, and make the most of what’s already in your kitchen.', resultsFromPantry: 'Recipes from your kitchen',
    backToRecipes: 'All recipes', recipeIndex: 'FROM THE RECIPE INDEX', demoData: 'DEMO DATA', timeNotSpecified: 'Time not specified', totalTimeNotSpecified: 'Total time not specified', activeTime: 'Active {minutes} min', passiveTime: 'Passive {minutes} min', difficultyNotSpecified: 'Difficulty not specified', ingredientCount: '{count} ingredients', prepareIngredients: 'GET EVERYTHING READY', beforeStart: 'Before you start', miseEnPlace: 'Mise en place', equipmentNeeded: 'Equipment needed', ingredients: 'Ingredients', serves: 'Serves', optional: 'Optional', servingNote: 'Some ingredients may need a practical adjustment when servings change.', methodEyebrow: 'TAKE IT ONE STEP AT A TIME', method: 'Method', timingNotSpecified: 'No timing specified', minutes: '{minutes} min', source: 'Recipe source', sourceNotSpecified: 'Not specified in the source recipe.', loadingRecipe: 'Loading recipe…', recipeOpenError: 'We couldn’t open this recipe.', everydayCooking: 'Everyday cooking', photoUnavailable: 'Photo not available', viewRecipe: 'View {title}', notSpecified: 'Not specified', notSpecifiedInSource: 'Not specified in the source recipe.', servingsCount: '{count} servings', easy: 'Easy', medium: 'Medium', advanced: 'Advanced', decreaseServings: 'Decrease servings', increaseServings: 'Increase servings', compact: 'Compact', detailed: 'Detailed', printRecipe: 'Print recipe', startCooking: 'Start cooking', prepPhase: 'Prep', cookPhase: 'Cook', finishPhase: 'Finish', servePhase: 'Serve', phaseNotSpecified: 'Step', heatLevel: 'Heat', temperature: 'Temperature', lookFor: 'Look for', sensoryCue: 'Smell / sound', donenessCue: 'Done when', tip: 'Tip', commonMistake: 'Common mistake', ifThisHappens: 'If this happens', safetyNote: 'Safety note', substitutions: 'Substitutions', troubleshooting: 'Troubleshooting', storage: 'Storage and reheating', servingSuggestions: 'Serving suggestions', variations: 'Variations', foodSafety: 'Food safety', allergies: 'Allergen notes', noMise: 'No preparation checklist is specified in the source recipe.',
    notFoundEyebrow: '404 / NOTHING IN THE PAN', notFoundTitle: 'This page isn’t on the menu.', backHome: 'Back to RecipeMaster',
  },
  ta: {
    navRecipes: 'சமையல் குறிப்புகள்', navCuisines: 'உணவு வகைகள்', navAbout: 'எங்களைப் பற்றி', findMeal: 'அடுத்த உணவைக் கண்டறியுங்கள்', homeLabel: 'ரெசிப்பி மாஸ்டர் முகப்பு', mainNavigation: 'முதன்மை வழிசெலுத்தல்', dietLabel: 'உணவு முறை', cuisineLabel: 'உணவு வகை', maxTimeLabel: 'அதிகபட்ச சமையல் நேரம்', sortLabel: 'குறிப்புகளை வரிசைப்படுத்து', searchActionLabel: 'சமையல் குறிப்புகளைத் தேடு',
    heroEyebrow: 'அன்றாட வாழ்க்கைக்கான சமையல் குறிப்பு', heroTitleLead: 'உங்களிடம் இருப்பதை வைத்து', heroTitleEm: 'சமைக்கலாம்.', heroIntro: 'உங்கள் சமையலறையில் ஏற்கனவே உள்ள பொருட்களுக்கான சிறிய உத்வேகம்.', heroFind: 'சமையல் குறிப்பைக் காண்க', heroNote: 'எங்கிருந்தாலும், அன்றாட சமையலறைகளுக்காக.', heroPhotoLabel: 'நல்ல உணவு, எளிய சமையல்', heroPhotoKicker: '01 / அன்றாடம்', heroImageAlt: 'வீட்டில் செய்த பருப்பு மற்றும் காய்கறி குழம்பு',
    flowScan: 'படமெடு', flowConfirm: 'உறுதிசெய்', flowCook: 'சமை', flowWaste: 'வீணாக்காதே', indexEyebrow: 'சமையல் குறிப்பு தொகுப்பு', compactRecipesHeading: 'இங்கிருந்து தொடங்கலாம்', recipesHeading: 'நல்லதைத் தேடுங்கள்', recipesCount: '{count} குறிப்புகள்', searchLabel: 'சமையல் குறிப்பு அல்லது பொருளைத் தேடுங்கள்', searchPlaceholder: 'தக்காளி, பருப்பு அல்லது அரிசி எனத் தேடுங்கள்',
    anyDiet: 'எந்த உணவும்', vegetarian: 'சைவம்', vegan: 'வீகன்', glutenFree: 'குளூட்டன் இல்லாதது', anyCuisine: 'எந்த வகையும்', southIndian: 'தென்னிந்திய', northIndian: 'வடஇந்திய', eastAsian: 'கிழக்காசிய பாணி', tamilCuisine: 'தமிழ்', anyTime: 'எந்த நேரமும்', under20: '20 நிமிடத்திற்குள்', under30: '30 நிமிடத்திற்குள்', under45: '45 நிமிடத்திற்குள்', recentlyAdded: 'புதிதாகச் சேர்த்தவை', shortestTime: 'குறைந்த நேரம்', mostSaved: 'அதிகம் சேமித்தவை', search: 'தேடு', filterSummary: 'உங்கள் இருப்பில் உள்ள பொருட்களுக்காக.', clearFilters: 'வடிகட்டிகளை நீக்கு', loadingRecipes: 'உங்கள் சமையலறைக்கான குறிப்புகளைத் தேடுகிறது…', recipesErrorTitle: 'குறிப்புகளை இப்போது பெற முடியவில்லை.', apiOffline: 'சமையல் தரவு தற்காலிகமாக கிடைக்கவில்லை. MongoDB இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.', apiUnreachable: 'RecipeMaster-ஐ அணுக முடியவில்லை. API இயங்குகிறதா எனச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.', genericLoadError: 'குறிப்புகளை ஏற்றும்போது பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.', notFoundError: 'அந்த சமையல் குறிப்பு கிடைக்கவில்லை.', tryAgain: 'மீண்டும் முயற்சி', quotaExceeded: 'இன்றைய {limit} தேடல்களையும் பயன்படுத்திவிட்டீர்கள். {reset} மணிக்கு மீண்டும் கிடைக்கும்.', noRecipes: 'சமையல் குறிப்புகள் இன்னும் இல்லை.', emptyRecipes: 'வேறு சொற்களால் தேடுங்கள் அல்லது MongoDB-ஐ இணைத்த பிறகு seed கட்டளையால் demo குறிப்புகளைச் சேர்க்கவும்.', browseAll: 'அனைத்து குறிப்புகளையும் காண்க', pageLabel: 'பக்கம் {page} / {pages}', previous: 'முந்தையது', next: 'அடுத்தது',
    worldEyebrow: 'உலகெங்கும் வீட்டு சமையல்', cuisineTitleFirst: 'உங்களுக்குப் பிடித்த', cuisineTitleSecond: 'சுவையிலிருந்து தொடங்குங்கள்.', everydayFavourites: 'அன்றாட விருப்பங்கள்', aboutEyebrow: 'கவனமான சமையலறை', aboutText: 'ஒவ்வொரு படியாகச் சமைக்கவும். இருப்புப் பொருட்களைப் பதிவு செய்யவும். முதலில் பயன்படுத்த வேண்டிய பொருட்களிலிருந்து அடுத்த உணவைத் தொடங்குங்கள்.', exploreRecipes: 'குறிப்புகளைப் பாருங்கள்', footerTagline: 'உங்களிடம் இருப்பதை வைத்து சமைக்கலாம்.', footerCredit: 'ஒவ்வொரு உணவிலும் வீணாவதைக் குறைப்போம்.',
    pageEyebrow: 'உங்களிடம் இருப்பதை வைத்து சமைக்கவும்', pageTitle: 'சமையல் குறிப்பு தொகுப்பு', pageIntro: 'பொருளின் பெயரால் தேடி, புதிய விருப்பத்தைக் கண்டறிந்து, சமையலறையில் உள்ளவற்றைப் பயன்படுத்துங்கள்.', resultsFromPantry: 'உங்கள் சமையலறைக்கான குறிப்புகள்',
    backToRecipes: 'அனைத்து குறிப்புகளும்', recipeIndex: 'சமையல் குறிப்பு தொகுப்பிலிருந்து', demoData: 'மாதிரி தரவு', timeNotSpecified: 'நேரம் குறிப்பிடப்படவில்லை', totalTimeNotSpecified: 'மொத்த நேரம் குறிப்பிடப்படவில்லை', activeTime: 'செயல் நேரம் {minutes} நிமிடம்', passiveTime: 'காத்திருப்பு {minutes} நிமிடம்', difficultyNotSpecified: 'கடினத்தன்மை குறிப்பிடப்படவில்லை', ingredientCount: '{count} பொருட்கள்', prepareIngredients: 'தேவையானவற்றைத் தயார் செய்யுங்கள்', beforeStart: 'தொடங்குவதற்கு முன்', miseEnPlace: 'முன்தயாரிப்பு', equipmentNeeded: 'தேவையான உபகரணங்கள்', ingredients: 'தேவையான பொருட்கள்', serves: 'பரிமாறல்', optional: 'விருப்பத்தேர்வு', servingNote: 'பரிமாறும் எண்ணிக்கையை மாற்றும்போது சில அளவுகளைச் சரிசெய்ய வேண்டியிருக்கலாம்.', methodEyebrow: 'ஒவ்வொரு படியாகச் செய்யுங்கள்', method: 'செய்முறை', timingNotSpecified: 'நேரம் குறிப்பிடப்படவில்லை', minutes: '{minutes} நிமிடம்', source: 'குறிப்பின் மூலம்', sourceNotSpecified: 'மூலக் குறிப்பில் குறிப்பிடப்படவில்லை.', loadingRecipe: 'குறிப்பை ஏற்றுகிறது…', recipeOpenError: 'இந்தக் குறிப்பைத் திறக்க முடியவில்லை.', everydayCooking: 'அன்றாட சமையல்', photoUnavailable: 'படம் கிடைக்கவில்லை', viewRecipe: '{title} குறிப்பைப் பார்க்கவும்', notSpecified: 'குறிப்பிடப்படவில்லை', notSpecifiedInSource: 'மூலக் குறிப்பில் குறிப்பிடப்படவில்லை.', servingsCount: '{count} பேருக்கான அளவு', easy: 'எளிது', medium: 'நடுத்தரம்', advanced: 'கடினம்', decreaseServings: 'பரிமாறும் எண்ணிக்கையைக் குறைக்கவும்', increaseServings: 'பரிமாறும் எண்ணிக்கையை அதிகரிக்கவும்', compact: 'சுருக்கம்', detailed: 'விரிவாக', printRecipe: 'குறிப்பை அச்சிடு', startCooking: 'சமைக்கத் தொடங்கு', prepPhase: 'முன்தயாரிப்பு', cookPhase: 'சமைத்தல்', finishPhase: 'இறுதிப்பணி', servePhase: 'பரிமாறு', phaseNotSpecified: 'படி', heatLevel: 'சூடு', temperature: 'வெப்பநிலை', lookFor: 'கவனிக்கவும்', sensoryCue: 'மணம் / ஒலி', donenessCue: 'தயாரான அறிகுறி', tip: 'குறிப்பு', commonMistake: 'பொதுவான தவறு', ifThisHappens: 'இது நடந்தால்', safetyNote: 'பாதுகாப்புக் குறிப்பு', substitutions: 'மாற்றுப் பொருட்கள்', troubleshooting: 'சிக்கல் தீர்வு', storage: 'சேமித்தல் மற்றும் மீண்டும் சூடாக்குதல்', servingSuggestions: 'பரிமாறும் யோசனைகள்', variations: 'மாற்றங்கள்', foodSafety: 'உணவுப் பாதுகாப்பு', allergies: 'ஒவ்வாமைக் குறிப்புகள்', noMise: 'மூலக் குறிப்பில் முன்தயாரிப்பு பட்டியல் குறிப்பிடப்படவில்லை.',
    notFoundEyebrow: '404 / இந்தப் பக்கம் இல்லை', notFoundTitle: 'இந்தப் பக்கம் பட்டியலில் இல்லை.', backHome: 'RecipeMaster முகப்புக்குச் செல்லுங்கள்',
  },
  hi: {
    navRecipes: 'रेसिपी', navCuisines: 'व्यंजन', navAbout: 'परिचय', findMeal: 'अपना अगला भोजन खोजें', homeLabel: 'RecipeMaster होम', mainNavigation: 'मुख्य नेविगेशन', dietLabel: 'आहार', cuisineLabel: 'व्यंजन', maxTimeLabel: 'खाना पकाने का अधिकतम समय', sortLabel: 'रेसिपी क्रमबद्ध करें', searchActionLabel: 'रेसिपी खोजें',
    heroEyebrow: 'रोज़मर्रा की रसोई के लिए', heroTitleLead: 'आपके पास जो है, उससे', heroTitleEm: 'पकाएँ।', heroIntro: 'आपकी रसोई में पहले से मौजूद सामग्री से कुछ नया बनाने की प्रेरणा।', heroFind: 'रेसिपी खोजें', heroNote: 'हर जगह की रोज़मर्रा की रसोई के लिए।', heroPhotoLabel: 'अच्छा खाना, कम उलझन', heroPhotoKicker: '01 / रोज़मर्रा', heroImageAlt: 'घर की बनी दाल और सब्ज़ियों का कटोरा',
    flowScan: 'स्कैन', flowConfirm: 'पुष्टि', flowCook: 'पकाएँ', flowWaste: 'बर्बादी घटाएँ', indexEyebrow: 'रेसिपी संग्रह', compactRecipesHeading: 'यहाँ से शुरू करें', recipesHeading: 'कुछ अच्छा खोजें', recipesCount: '{count} रेसिपी', searchLabel: 'रेसिपी या सामग्री खोजें', searchPlaceholder: 'टमाटर, दाल या चावल खोजें',
    anyDiet: 'कोई भी आहार', vegetarian: 'शाकाहारी', vegan: 'वीगन', glutenFree: 'ग्लूटेन-मुक्त', anyCuisine: 'कोई भी व्यंजन', southIndian: 'दक्षिण भारतीय', northIndian: 'उत्तर भारतीय', eastAsian: 'पूर्वी एशियाई शैली', tamilCuisine: 'तमिल', anyTime: 'कोई भी समय', under20: '20 मिनट से कम', under30: '30 मिनट से कम', under45: '45 मिनट से कम', recentlyAdded: 'हाल ही में जोड़ी गई', shortestTime: 'सबसे कम समय', mostSaved: 'सबसे अधिक सहेजी गई', search: 'खोजें', filterSummary: 'आपकी रसोई में पहले से मौजूद चीज़ों के लिए।', clearFilters: 'फ़िल्टर हटाएँ', loadingRecipes: 'आपकी रसोई के लिए रेसिपी खोज रहे हैं…', recipesErrorTitle: 'रेसिपी अभी उपलब्ध नहीं हैं।', apiOffline: 'रेसिपी डेटा अभी उपलब्ध नहीं है। MongoDB कनेक्शन जाँचकर फिर कोशिश करें।', apiUnreachable: 'RecipeMaster तक पहुँचा नहीं जा सका। API चल रही है या नहीं जाँचकर फिर कोशिश करें।', genericLoadError: 'रेसिपी लोड करते समय कुछ गड़बड़ हुई। फिर कोशिश करें।', notFoundError: 'यह रेसिपी नहीं मिली।', tryAgain: 'फिर कोशिश करें', quotaExceeded: 'आज की {limit} रेसिपी खोजें पूरी हो गईं। {reset} बजे फिर कोशिश करें।', noRecipes: 'अभी कोई रेसिपी नहीं मिली।', emptyRecipes: 'खोज को थोड़ा व्यापक करें, या MongoDB कनेक्ट करने के बाद seed कमांड से डेमो रेसिपी जोड़ें।', browseAll: 'सभी रेसिपी देखें', pageLabel: 'पृष्ठ {page} / {pages}', previous: 'पिछला', next: 'अगला',
    worldEyebrow: 'दुनिया भर के घरों का खाना', cuisineTitleFirst: 'अपने पसंदीदा', cuisineTitleSecond: 'स्वाद से शुरू करें।', everydayFavourites: 'रोज़मर्रा के पसंदीदा', aboutEyebrow: 'सोच-समझकर बनी रसोई', aboutText: 'एक-एक कदम करके पकाएँ। अपनी सामग्री का हिसाब रखें। अगला भोजन उन चीज़ों से शुरू करें जिन्हें पहले इस्तेमाल करना है।', exploreRecipes: 'रेसिपी देखें', footerTagline: 'आपके पास जो है, उससे कुछ पकाएँ।', footerCredit: 'हर भोजन के साथ बर्बादी थोड़ी कम।',
    pageEyebrow: 'आपके पास जो है, उससे पकाएँ', pageTitle: 'रेसिपी संग्रह', pageIntro: 'सामग्री के आधार पर खोजें, नया पसंदीदा ढूँढें और रसोई में मौजूद चीज़ों का बेहतर उपयोग करें।', resultsFromPantry: 'आपकी रसोई की रेसिपी',
    backToRecipes: 'सभी रेसिपी', recipeIndex: 'रेसिपी संग्रह से', demoData: 'डेमो डेटा', timeNotSpecified: 'समय नहीं दिया गया', totalTimeNotSpecified: 'कुल समय नहीं दिया गया', activeTime: 'सक्रिय समय {minutes} मिनट', passiveTime: 'प्रतीक्षा {minutes} मिनट', difficultyNotSpecified: 'कठिनाई नहीं बताई गई', ingredientCount: '{count} सामग्री', prepareIngredients: 'सामग्री तैयार करें', beforeStart: 'शुरू करने से पहले', miseEnPlace: 'पहले से तैयारी', equipmentNeeded: 'ज़रूरी उपकरण', ingredients: 'सामग्री', serves: 'लोगों के लिए', optional: 'वैकल्पिक', servingNote: 'परोसने की संख्या बदलने पर कुछ मात्रा व्यावहारिक रूप से समायोजित करनी पड़ सकती है।', methodEyebrow: 'एक बार में एक कदम', method: 'विधि', timingNotSpecified: 'समय नहीं दिया गया', minutes: '{minutes} मिनट', source: 'रेसिपी स्रोत', sourceNotSpecified: 'मूल रेसिपी में नहीं बताया गया।', loadingRecipe: 'रेसिपी लोड हो रही है…', recipeOpenError: 'यह रेसिपी नहीं खुल सकी।', everydayCooking: 'रोज़मर्रा का खाना', photoUnavailable: 'फ़ोटो उपलब्ध नहीं', viewRecipe: '{title} रेसिपी देखें', notSpecified: 'नहीं बताया गया', notSpecifiedInSource: 'मूल रेसिपी में नहीं बताया गया।', servingsCount: '{count} लोगों के लिए', easy: 'आसान', medium: 'मध्यम', advanced: 'कठिन', decreaseServings: 'परोसने की संख्या घटाएँ', increaseServings: 'परोसने की संख्या बढ़ाएँ', compact: 'संक्षिप्त', detailed: 'विस्तृत', printRecipe: 'रेसिपी प्रिंट करें', startCooking: 'पकाना शुरू करें', prepPhase: 'तैयारी', cookPhase: 'पकाना', finishPhase: 'अंतिम चरण', servePhase: 'परोसें', phaseNotSpecified: 'कदम', heatLevel: 'आँच', temperature: 'तापमान', lookFor: 'देखें', sensoryCue: 'खुशबू / आवाज़', donenessCue: 'तैयार होने का संकेत', tip: 'सुझाव', commonMistake: 'आम गलती', ifThisHappens: 'ऐसा हो तो', safetyNote: 'सुरक्षा नोट', substitutions: 'विकल्प', troubleshooting: 'समस्या का समाधान', storage: 'भंडारण और दोबारा गरम करना', servingSuggestions: 'परोसने के सुझाव', variations: 'बदलाव', foodSafety: 'खाद्य सुरक्षा', allergies: 'एलर्जी नोट', noMise: 'मूल रेसिपी में तैयारी सूची नहीं दी गई।',
    notFoundEyebrow: '404 / पेज नहीं मिला', notFoundTitle: 'यह पेज मेनू में नहीं है।', backHome: 'RecipeMaster होम पर जाएँ',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  function t(key, values = {}) {
    let message = messages[language]?.[key] || messages.en[key] || key;
    for (const [name, value] of Object.entries(values)) {
      message = message.replaceAll(`{${name}}`, String(value));
    }
    return message;
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}